
import Foundation

struct Rwy: Codable {
	let arptIdent: String? 	let highIdent: String? 	let lowIdent: String? 	let highHdg: String? 	let lowHdg: String? 	let length: String? 	let rwyWidth: String? 	let surface: String? 	let pcn: String? 	let heWgsLat: String? 	let heWgsDlat: String? 	let heWgsLong: String? 	let heWgsDlong: String? 	let heElev: String? 	let heSlope: String? 	let heTdze: String? 	let heDt: String? 	let heDtElev: String? 	let hlgtSys1: String? 	let hlgtSys2: String? 	let hlgtSys3: String? 	let hlgtSys4: String? 	let hlgtSys5: String? 	let hlgtSys6: String? 	let hlgtSys7: String? 	let hlgtSys8: String? 	let leWgsLat: String? 	let leWgsDlat: String? 	let leWgsLong: String? 	let leWgsDlong: String? 	let leElev: String? 	let leSlope: String? 	let leTdze: String? 	let leDt: String? 	let leDtElev: String? 	let llgtSys1: String? 	let llgtSys2: String? 	let llgtSys3: String? 	let llgtSys4: String? 	let llgtSys5: String? 	let llgtSys6: String? 	let llgtSys7: String? 	let llgtSys8: String? 	let heTrueHdg: String? 	let leTrueHdg: String? 	let cldRwy: String? 	let helandDis: String? 	let heTakeoff: String? 	let lelandDis: String? 	let leTakeoff: String? 	let cycleDate: String? 


	enum CodingKeys: String, CodingKey {
		case arptIdent = "ARPT_IDENT"		case highIdent = "HIGH_IDENT"		case lowIdent = "LOW_IDENT"		case highHdg = "HIGH_HDG"		case lowHdg = "LOW_HDG"		case length = "LENGTH"		case rwyWidth = "RWY_WIDTH"		case surface = "SURFACE"		case pcn = "PCN"		case heWgsLat = "HE_WGS_LAT"		case heWgsDlat = "HE_WGS_DLAT"		case heWgsLong = "HE_WGS_LONG"		case heWgsDlong = "HE_WGS_DLONG"		case heElev = "HE_ELEV"		case heSlope = "HE_SLOPE"		case heTdze = "HE_TDZE"		case heDt = "HE_DT"		case heDtElev = "HE_DT_ELEV"		case hlgtSys1 = "HLGT_SYS_1"		case hlgtSys2 = "HLGT_SYS_2"		case hlgtSys3 = "HLGT_SYS_3"		case hlgtSys4 = "HLGT_SYS_4"		case hlgtSys5 = "HLGT_SYS_5"		case hlgtSys6 = "HLGT_SYS_6"		case hlgtSys7 = "HLGT_SYS_7"		case hlgtSys8 = "HLGT_SYS_8"		case leWgsLat = "LE_WGS_LAT"		case leWgsDlat = "LE_WGS_DLAT"		case leWgsLong = "LE_WGS_LONG"		case leWgsDlong = "LE_WGS_DLONG"		case leElev = "LE_ELEV"		case leSlope = "LE_SLOPE"		case leTdze = "LE_TDZE"		case leDt = "LE_DT"		case leDtElev = "LE_DT_ELEV"		case llgtSys1 = "LLGT_SYS_1"		case llgtSys2 = "LLGT_SYS_2"		case llgtSys3 = "LLGT_SYS_3"		case llgtSys4 = "LLGT_SYS_4"		case llgtSys5 = "LLGT_SYS_5"		case llgtSys6 = "LLGT_SYS_6"		case llgtSys7 = "LLGT_SYS_7"		case llgtSys8 = "LLGT_SYS_8"		case heTrueHdg = "HE_TRUE_HDG"		case leTrueHdg = "LE_TRUE_HDG"		case cldRwy = "CLD_RWY"		case helandDis = "HELAND_DIS"		case heTakeoff = "HE_TAKEOFF"		case lelandDis = "LELAND_DIS"		case leTakeoff = "LE_TAKEOFF"		case cycleDate = "CYCLE_DATE"
}
}